name: Build and deploy Vue.js app to Azure Web App - pr-checklist

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Zip build artifact for deployment
        run: zip -r release.zip dist/*

      - name: Upload build artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: vue-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download build artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: vue-app

      - name: Unzip build artifact for deployment
        run: unzip release.zip -d dist

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pr-checklist'
          slot-name: 'Production'
          package: dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7BD839E361C54E108B82E357D9BEA85A }}
